import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AnimatePresence, motion} from 'framer-motion';
import {Menu, X, ShoppingBag, Star, ArrowRight, Search, Plus, Minus, Trash2, MapPin, Phone, Mail, ChefHat, Wheat, Heart, Zap, CalendarDays, Leaf, Flame} from 'lucide-react';
import './style.css';

const photos={hero:'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1800&q=85',pasta:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80',paneer:'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=900&q=80',pizza:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=80',biryani:'https://images.unsplash.com/photo-1631515242808-497c3fbd3972?auto=format&fit=crop&w=900&q=80',interior:'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=85',chef:'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=900&q=80',dessert:'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=900&q=80',burger:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80'};
const dishes=[
 {id:1,name:'Truffle Wild Mushroom Pasta',desc:'Handmade tagliatelle, porcini cream, parmesan',price:595,cat:'Main Course',img:photos.pasta,veg:true,best:true},
 {id:2,name:'Charred Paneer Tikka',desc:'Smoky cottage cheese, mint yoghurt, pickled onion',price:385,cat:'Starters',img:photos.paneer,veg:true,best:true},
 {id:3,name:'Saffron Lamb Biryani',desc:'Slow-cooked lamb, aged basmati, crispy onions',price:645,cat:'Biryani/Rice',img:photos.biryani,veg:false,spicy:true},
 {id:4,name:'Ember Woodfired Pizza',desc:'Burrata, roasted tomatoes, fresh basil',price:525,cat:'Pizza',img:photos.pizza,veg:true},
 {id:5,name:'Firehouse Smash Burger',desc:'Angus patty, cheddar, house pickles, brioche',price:495,cat:'Burgers',img:photos.burger,veg:false,best:true},
 {id:6,name:'Chilli Garlic Noodles',desc:'Wok-tossed vegetables, toasted sesame, soy',price:365,cat:'Chinese',img:photos.pasta,veg:true,spicy:true},
 {id:7,name:'Dark Chocolate Fondant',desc:'Molten centre, vanilla bean gelato',price:295,cat:'Desserts',img:photos.dessert,veg:true},
 {id:8,name:'Hibiscus Cooler',desc:'Rose, citrus, sparkling water, mint',price:175,cat:'Beverages',img:photos.hero,veg:true}
];
const cats=['All','Starters','Main Course','Biryani/Rice','Pizza','Burgers','Chinese','Desserts','Beverages'];
const Reveal=({children,className=''})=><motion.div className={className} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.14}} transition={{duration:.55}}>{children}</motion.div>;
function App(){const [cartOpen,setCartOpen]=useState(false),[navOpen,setNavOpen]=useState(false),[scrolled,setScrolled]=useState(false),[cart,setCart]=useState([]),[filter,setFilter]=useState('All'),[query,setQuery]=useState(''),[lightbox,setLightbox]=useState(null),[sent,setSent]=useState(''); useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>30);onScroll();window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[]); const add=d=>setCart(c=>{let x=c.find(i=>i.id===d.id);return x?c.map(i=>i.id===d.id?{...i,qty:i.qty+1}:i):[...c,{...d,qty:1}]}); const adjust=(id,n)=>setCart(c=>c.map(i=>i.id===id?{...i,qty:i.qty+n}:i).filter(i=>i.qty)); const shown=dishes.filter(d=>(filter==='All'||d.cat===filter)&&d.name.toLowerCase().includes(query.toLowerCase())); const total=cart.reduce((a,i)=>a+i.price*i.qty,0); const links=['Home','About','Menu','Gallery','Reviews','Contact']; const submitReservation=async e=>{e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));try{const response=await fetch('/api/reservations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.message);setSent(result.message);form.reset()}catch(error){setSent(error.message||'Unable to send your request. Please call us directly.')}}; const checkout=async()=>{try{const response=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:cart,total})});const result=await response.json();if(!response.ok)throw new Error(result.message);alert(result.message);setCart([]);setCartOpen(false)}catch(error){alert(error.message||'Unable to place your order. Please try again.')}};
return <><header className={'topbar '+(scrolled?'topbar-scrolled':'')}><a href="#home" className="brand"><span>S</span><b>Saffron<br/> & Ember</b></a><nav>{links.map(x=><a href={'#'+x.toLowerCase()} key={x}>{x}</a>)}</nav><div className="nav-actions"><a className="btn btn-small" href="#reserve">Book a Table</a><button className="cart" aria-label="Open cart" onClick={()=>setCartOpen(true)}><ShoppingBag size={19}/>{cart.length>0&&<i>{cart.reduce((a,b)=>a+b.qty,0)}</i>}</button><button className="mobile-toggle" onClick={()=>setNavOpen(true)} aria-label="Open navigation"><Menu/></button></div></header><AnimatePresence>{navOpen&&<motion.div className="mobile-nav" initial={{opacity:0,y:-15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-15}}><button onClick={()=>setNavOpen(false)} aria-label="Close navigation"><X/></button>{links.map(x=><a onClick={()=>setNavOpen(false)} href={'#'+x.toLowerCase()} key={x}>{x}</a>)}<a onClick={()=>setNavOpen(false)} className="btn" href="#reserve">Book a table</a></motion.div>}</AnimatePresence>
<section id="home" className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(20,16,13,.86),rgba(20,16,13,.41)),url(${photos.hero})`}}><div className="hero-content"><motion.p initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="eyebrow">EST. 2014 Â· NEW DELHI</motion.p><motion.h1 initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:.12}}>A table set for<br/><em>beautiful moments.</em></motion.h1><motion.p initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.24}} className="hero-copy">A contemporary kitchen celebrating Indiaâ€™s vibrant flavours with a distinctly worldly spirit.</motion.p><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.36}} className="hero-buttons"><a className="btn" href="#menu">Explore Menu <ArrowRight size={17}/></a><a className="text-btn" href="#reserve">Reserve your table</a></motion.div></div><div className="hero-badge"><Star size={15} fill="currentColor"/> Fresh ingredients Â· honest cooking Â· warm nights</div></section>
<main><section className="section specials"><Reveal><div className="heading-row"><div><p className="eyebrow dark">OUR SIGNATURES</p><h2>Chefâ€™s <em>specials</em></h2></div><a href="#menu" className="arrow-link">View full menu <ArrowRight size={18}/></a></div></Reveal><div className="special-grid">{dishes.slice(0,4).map((d,i)=><Reveal key={d.id} className="dish-card"><div className="food-img"><img src={d.img} alt={d.name}/>{d.best&&<span className="badge">Bestseller</span>}<span className={'dot '+(d.veg?'veg':'nonveg')}></span></div><div className="dish-body"><div><h3>{d.name}</h3><p>{d.desc}</p></div><div className="dish-bottom"><strong>â‚¹{d.price}</strong><button onClick={()=>add(d)} aria-label={'Add '+d.name}><Plus size={18}/></button></div></div></Reveal>)}</div></section>
<section id="about" className="about section"><Reveal className="about-images"><img className="big-img" src={photos.interior} alt="Warm restaurant interior"/><div className="experience"><span>10<sup>+</sup></span><p>years of<br/>good taste</p></div><img className="float-img" src={photos.chef} alt="Chef preparing food"/></Reveal><Reveal className="about-copy"><p className="eyebrow dark">OUR STORY</p><h2>Where flavour meets <em>feeling.</em></h2><p>At Saffron & Ember, food is our favourite way to bring people closer. What began as a small open kitchen is now a beloved neighbourhood table, where every plate carries care, curiosity, and a little spark.</p><p>Our chefs work with seasonal produce and time-honoured techniques to make familiar flavours feel newly unforgettable.</p><div className="stats">{[['50+','Dishes on our menu'],['10K+','Happy guests'],['4.8','Average rating']].map(([n,l])=><div key={n}><b>{n}{n==='4.8'&&<Star size={13} fill="currentColor"/>}</b><span>{l}</span></div>)}</div><a href="#reserve" className="text-btn dark-link">Discover our story <ArrowRight size={16}/></a></Reveal></section>
<section id="menu" className="menu-section"><Reveal><p className="eyebrow dark">SOMETHING FOR EVERY MOOD</p><h2>From our <em>kitchen</em></h2><div className="menu-toolbar"><div className="categories">{cats.map(c=><button onClick={()=>setFilter(c)} className={filter===c?'selected':''} key={c}>{c}</button>)}</div><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search dishes..."/></label></div></Reveal><motion.div layout className="menu-grid">{shown.map(d=><motion.article layout initial={{opacity:0}} animate={{opacity:1}} key={d.id} className="menu-item"><img src={d.img} alt={d.name} loading="lazy"/><div><div className="menu-name"><h3>{d.name}</h3><span className={'dot '+(d.veg?'veg':'nonveg')}></span></div><p>{d.desc}</p><div className="dish-bottom"><strong>â‚¹{d.price}</strong><button onClick={()=>add(d)}>Add <Plus size={15}/></button></div></div></motion.article>)}</motion.div></section>
<section className="reasons"><Reveal><p className="eyebrow">THE SAFFRON & EMBER WAY</p><h2>Made with <em>intention.</em></h2><div className="reason-grid">{[[Wheat,'Seasonal ingredients','Only the best from trusted local producers.'],[ChefHat,'Thoughtful craft','Technique and instinct in every dish.'],[Heart,'Warm hospitality','You arrive as guests, you leave as friends.'],[Zap,'Good food, right on time','A dining experience paced just for you.'],[Leaf,'Freshly prepared','Every plate is cooked only once you order.'],[Flame,'Ember-fired flavour','A touch of flame brings depth to our kitchen.']].map(([Icon,t,x])=><div className="reason" key={t}><Icon/><h3>{t}</h3><p>{x}</p></div>)}</div></Reveal></section>
<section id="gallery" className="section gallery"><Reveal><p className="eyebrow dark">A GLIMPSE INSIDE</p><h2>Come for the food,<br/><em>stay for the mood.</em></h2></Reveal><div className="gallery-grid">{[photos.interior,photos.paneer,photos.chef,photos.pizza,photos.dessert,photos.biryani].map((p,i)=><button key={p+i} className={'gallery-img g'+i} onClick={()=>setLightbox(p)}><img src={p} alt="Saffron and Ember gallery" loading="lazy"/><span>View</span></button>)}</div></section>
<section id="reviews" className="reviews"><Reveal><p className="eyebrow dark">GUEST NOTES</p><h2>Love from our <em>table.</em></h2><div className="review-list">{[['Ananya Sharma','A beautiful place for a slow dinner. The lamb biryani was exceptional and the staff made us feel completely at home.'],['Rohan Mehta','The kind of restaurant you keep thinking about days later. Wonderful food, lovely ambience, genuinely kind service.'],['Maya Kapoor','Every course was beautifully presented and bursting with flavour. Our new favourite spot in the city.'],['Kabir Singh','The team paid attention to every little detail. Delicious, elegant and such a welcoming room.']].map(([n,t],i)=><article className="review" key={n}><div className="review-top"><div className="avatar">{n[0]}</div><div><h3>{n}</h3><span>{[1,2,3,4,5].map(x=><Star key={x} size={13} fill="currentColor"/>)}</span></div></div><p>â€œ{t}â€</p></article>)}</div></Reveal></section>
<section className="offer" style={{backgroundImage:`linear-gradient(90deg,rgba(21,17,14,.78),rgba(21,17,14,.38)),url(${photos.biryani})`}}><Reveal><p className="eyebrow">THIS WEEKEND ONLY</p><h2>More to <em>savour.</em></h2><p>Enjoy 20% off our chefâ€™s sharing menu every Saturday and Sunday.</p><a className="btn" href="#menu">Explore the offer <ArrowRight size={16}/></a></Reveal></section>
<section id="reserve" className="section reserve"><Reveal><div><p className="eyebrow dark">MAKE A RESERVATION</p><h2>Your seat at the<br/><em>table awaits.</em></h2><p>For groups of 8 or more, please call us directly. Weâ€™ll make it special.</p><div className="contact-mini"><Phone size={17}/> +91 98765 43210</div></div></Reveal><Reveal><form onSubmit={submitReservation}><div className="form-grid"><input name="fullName" required placeholder="Full name"/><input name="phone" required type="tel" placeholder="Phone number"/><input name="email" required type="email" placeholder="Email address"/><input name="date" required type="date"/><select name="time" required defaultValue=""><option value="" disabled>Preferred time</option><option>12:30 PM</option><option>7:00 PM</option><option>8:30 PM</option><option>9:30 PM</option></select><select name="guests" required defaultValue=""><option value="" disabled>Number of guests</option><option>2 guests</option><option>3 guests</option><option>4 guests</option><option>5+ guests</option></select></div><textarea name="request" placeholder="Anything we should know? (optional)" rows="3"></textarea><button className="btn" type="submit">Reserve my table <CalendarDays size={17}/></button>{sent&&<p className="success">{sent}</p>}</form></Reveal></section>
<section id="contact" className="contact"><div><p className="eyebrow">FIND US</p><h2>Come say <em>hello.</em></h2><p><MapPin size={17}/> Hamirpur, Uttar Pradesh, India</p><p><Phone size={17}/> +91 98765 43210</p><p><Mail size={17}/> hello@saffronandember.in</p></div><div><p className="eyebrow">OPENING HOURS</p><h3>Every day</h3><p>Lunch Â· 12:00 PM â€“ 3:30 PM</p><p>Dinner Â· 6:30 PM â€“ 11:30 PM</p><div className="contact-actions"><a href="tel:+919876543210"><Phone size={17}/> Call</a><a href="https://wa.me/919876543210" target="_blank"><Heart size={17}/> WhatsApp</a><a href="mailto:hello@saffronandember.in"><Mail size={17}/> Email</a></div></div><iframe className="map" title="Saffron and Ember location in Hamirpur" loading="lazy" src="https://www.google.com/maps?q=Hamirpur,+Uttar+Pradesh,+India&output=embed"></iframe></section></main>
<footer><div><a href="#home" className="brand"><span>S</span><b>Saffron<br/> & Ember</b></a><p>Modern Indian dining, made memorable.</p></div><div className="footer-links"><b>Explore</b><a href="#menu">Menu</a><a href="#about">Our story</a><a href="#gallery">Gallery</a><a href="#contact">Contact</a></div><div className="socials"><b>Follow along</b><a href="https://instagram.com" target="_blank">Instagram</a><a href="https://facebook.com" target="_blank">Facebook</a><a href="https://youtube.com" target="_blank">YouTube</a></div><p className="copy">Â© 2026 Saffron & Ember. All rights reserved.</p></footer>
<AnimatePresence>{cartOpen&&<motion.aside className="cart-drawer" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}}><button className="close" onClick={()=>setCartOpen(false)}><X/></button><p className="eyebrow dark">YOUR ORDER</p><h2>Good choices.</h2>{cart.length===0?<p className="empty">Your bag is waiting for something delicious.</p>:<><div className="cart-items">{cart.map(i=><div className="cart-item" key={i.id}><img src={i.img} alt=""/><div><h3>{i.name}</h3><p>â‚¹{i.price}</p><div className="qty"><button onClick={()=>adjust(i.id,-1)}><Minus size={14}/></button><b>{i.qty}</b><button onClick={()=>adjust(i.id,1)}><Plus size={14}/></button></div></div><button className="remove" onClick={()=>adjust(i.id,-i.qty)}><Trash2 size={16}/></button></div>)}</div><div className="checkout"><p><span>Subtotal</span><b>â‚¹{total}</b></p><p><span>Taxes</span><b>Calculated at checkout</b></p><h3>Total <span>â‚¹{total}</span></h3><button className="btn" onClick={checkout}>Proceed to checkout</button></div></>}</motion.aside>}</AnimatePresence>{lightbox&&<div className="lightbox" onClick={()=>setLightbox(null)}><button><X/></button><img src={lightbox} alt="Gallery enlarged"/></div>}<div className="bottom-actions"><a href="tel:+919876543210"><Phone/>Call</a><a href="https://wa.me/919876543210"><Heart/>WhatsApp</a><a href="#reserve"><CalendarDays/>Book table</a></div></>}
createRoot(document.getElementById('root')).render(<App/>);

